Repository otaKenneth/laravel-e-commerce, pull requests merged in 2024-10, with the labels that each got.

#247 Shop Logo and Admin Products fxs
  app/Http/Controllers/Admin/AdminController.php
  app/Models/Vendor.php
  database/migrations/2024_10_07_122359_add_shop_logo_column_to_vendors_business_details_table.php
  public/admin/js/custom.js
  resources/views/admin/admins/view_vendor_details.blade.php
  resources/views/admin/settings/update_vendor_details.blade.php
  resources/views/front/pages/merchants.blade.php
  resources/views/front/products/detail.blade.php
Labels: bug, enhancement

#249 Kapiton feature/customer/content
  app/Http/Controllers/Front/VendorController.php
  app/Models/Vendor.php
  resources/views/front/pages/merchants.blade.php
  resources/views/front/products/detail.blade.php
Labels: bug, enhancement

#256 [Customer] Banners upload
  app/Http/Controllers/Admin/BannersController.php
Labels: bug

#259 Chats Feature fix
  app/Livewire/ChatBox.php
  resources/views/admin/chats/chat-list-of-merchant.blade.php
  resources/views/front/chats/chat-list-of-merchant.blade.php
  resources/views/livewire/admin/chat-box.blade.php
  resources/views/livewire/chat-box.blade.php
Labels: bug, enhancement

#262 DYNAMIC VARIANT
  .gitignore
  app/Http/Controllers/Admin/ProductsController.php
  app/Models/Product.php
  app/Models/ProductsVariant.php
  composer.lock
  database/migrations/2024_10_27_023443_create_products_variants_table.php
  public/admin/css/custom.css
  public/admin/js/custom.js
  resources/views/admin/attributes/add_edit_attributes.blade.php
  resources/views/livewire/admin/chat-box.blade.php
Labels: enhancement
