Repository otaKenneth/laravel-e-commerce, pull requests merged in 2024-07, with the labels that each got.

#170 Lalamove Webhook
  app/Http/Controllers/API/APIController.php
  routes/api.php
Labels: enhancement

#172 Lalamove Order processing and Error message
  app/Helpers/Helper.php
  app/Helpers/LalamoveAPIBodyHelper.php
  app/Http/Controllers/Admin/OrderController.php
  app/Models/Order.php
  resources/views/admin/settings/update_vendor_details.blade.php
Labels: bug

#180 Products URI fixes and Logs
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Controllers/Front/ProductsController.php
  app/Providers/AppServiceProvider.php
Labels: bug

#182 delivery address and map pin fix
  public/front/js/custom-user-account.js
  resources/views/front/users/delivery_addresses.blade.php
Labels: bug

#184 fx
  public/front/js/custom-user-account.js
Labels: bug

#188 Product order relationship fix
  app/Helpers/LalamoveAPIBodyHelper.php
  app/Http/Controllers/Admin/OrderController.php
  app/Models/Category.php
  app/Models/OrdersProduct.php
Labels: bug

#190 Vendor details fix inputs
  app/Http/Controllers/Admin/OrderController.php
  public/admin/js/custom.js
  resources/views/admin/settings/update_vendor_details.blade.php
Labels: bug

#192 lalamove webhook api
  app/Http/Controllers/API/APIController.php
Labels: enhancement

#194 Additional UI fx
  resources/views/admin/orders/order_details.blade.php
Labels: enhancement

#196 Paymongo & Lalamove payment computation
  app/Helpers/PaymongoAPIHelper.php
  app/Http/Controllers/Front/ProductsController.php
  public/front/js/custom.js
  resources/views/front/products/cart_items.blade.php
  resources/views/front/products/checkout.blade.php
Labels: bug

#201 thanks page fix
  resources/views/front/products/thanks.blade.php
Labels: bug

#205 Platform Management delete/update toasters
  app/Http/Controllers/Admin/PlatformContentController.php
  public/admin/js/custom.js
  resources/views/admin/platform_content/platform_content.blade.php
  resources/views/admin/platform_content/trusted_by_list.blade.php
  routes/web_admin.php
Labels: enhancement

#207 API update
  app/Http/Controllers/API/APIController.php
Labels: bug, enhancement

#209 [Customer] Orders and Cancel Order fxn
  app/Http/Controllers/Front/OrderController.php
  app/Models/Order.php
  public/front/js/custom.js
  resources/views/front/orders/orders.blade.php
  routes/web_customer.php
Labels: enhancement

#211 user account update
  app/Http/Kernel.php
  app/Http/Middleware/SetBreadcrumbs.php
  public/front/css/elementor-css/elementor-css-post-743.css
  resources/views/front/chats/chat.blade.php
  resources/views/front/layout/layout.blade.php
  resources/views/front/orders/orders.blade.php
  resources/views/front/users/delivery_addresses.blade.php
  resources/views/front/users/profile.blade.php
  resources/views/front/users/reset_password.blade.php
  resources/views/front/users/user_account.blade.php
  resources/views/front/users/wishlist.blade.php
  resources/views/livewire/admin/chat-box.blade.php
  resources/views/livewire/chat-box.blade.php
  routes/web_customer.php
Labels: enhancement

#212 remove unnecessary code
  resources/views/front/users/delivery_addresses.blade.php
  resources/views/front/users/reset_password.blade.php
  resources/views/front/users/user_account.blade.php
  resources/views/front/users/wishlist.blade.php
  resources/views/livewire/chat-box.blade.php
Labels: bug

#214 Paymongo refund
  app/Http/Controllers/API/APIController.php
Labels: bug

#217 Kapiton bugfix/orders
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Front/ProductsController.php
  app/Http/Controllers/Front/VendorController.php
  routes/web_customer.php
Labels: bug

#219 Cart/Checkout bug fixs
  app/Http/Controllers/Front/ProductsController.php
  public/front/js/custom.js
  resources/views/front/layout/layout.blade.php
  resources/views/front/products/cart_items.blade.php
  resources/views/front/products/detail.blade.php
  routes/web_customer.php
Labels: bug

#221 New Product - notify admins only
  app/Http/Controllers/Admin/ProductsController.php
  app/Http/Controllers/Front/ProductsController.php
  resources/views/admin/orders/orders.blade.php
Labels: bug
